version: "3.3"
services:
  controle_acesso:
    build: ./servico-controle-acesso/
    ports:
      - "5000:5000"
  habilidade:
    build: ./servico-habilidade/
    ports:
      - "5001:5001"
  plano_desenvolvimento:
    build: ./servico-plano-desenvolvimento/
    ports:
      - "5002:5002"
  gateway:
    build: ./gateway/
    ports:
      - "8000:8000"
  front:
    build: ./servico-front/
    ports:
      - "5003:5003"
