version: "3.3"
services:
  habilidade:
    build: ./servico-habilidade/
    ports:
      - "5001:5001"
  plano_desenvolvimento:
    build: ./servico-plano-desenvolvimento/
    ports:
      - "5002:5002"
  gatewat:
    build: ./gateway/
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/code
    # environment:
    #   FLASK_ENV: development
  # plano_desenvolvimento:
  #   build: ./servico-plano-desenvolvimento/
  #   ports:
  #     - "8761:8761"
  #   volumes:
  #     - .:/code
  #   environment:
  #     FLASK_ENV: development
  # controle_acesso:
  #   build: ./servico-controle-acesso/
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/code
  #   environment:
  #     FLASK_ENV: development
